elementary/onboarding

src/MainWindow.vala
So that it doesn't affect button size
=> MainWindow: set stackswitcher as a non-homogeneous child

src/Views/FinishView.vala, src/Views/WelcomeView.vala
@danrabbit and I were talking that the resources make more sense up front, and System Settings at the end. So this swaps them and tweaks the copy to make sense in the new context. Fixes #21.
=> Swap basic contents of Welcome and Finish views

src/MainWindow.vala
The crossfade doesn't hide the resizing that happens due to the homogeneous setting. Explicitly setting the transition to `NONE` makes it hide instantly before resizing.
=> No skip stack transition

src/Views/AppCenterView.vala
I think in this context it doesn't make sense to grab the OS name because elementary would never review apps for another OS
=> AppCenterView: hard code elementary OS

src/MainWindow.vala
As discussed in Slack. Gives a chance for undo, and prevents the case where someone thinks it's a back button and then doesn't know what just happened.
=> Make Skip go to Finish page

meson_options.txt, src/Application.vala, src/config.vala.in, src/meson.build
With a meson_options.txt as I can already hear Fedora and ArchLinux people screaming
Fixes https://github.com/elementary/default-settings/issues/117
=> Do not show onboarding on Guest sessions

data/io.elementary.onboarding.gschema.xml, po/POTFILES, src/Application.vala, src/MainWindow.vala, src/Views/AbstractOnboardingView.vala, src/Views/UpdateView.vala, src/meson.build
Based on something @danrabbit had mentioned. Basically, this would allow us to use onboarding to introduce new major features for existing installs by tracking which pages have been seen.
=> Show new pages on update

src/MainWindow.vala, src/Views/LocationServicesView.vala
Fixes #53. You can test by making sure the GeoClue agent is uninstalled, i.e.
```
sudo apt purge pantheon-agent-geoclue2
```
And make sure all views should show up:
```
gsettings reset io.elementary.onboarding viewed
```
…then run Onboarding and see that the Location Services view doesn't show up. Don't forget to reinstall the GeoClue agent for yourself. :)
=> Check for GeoClue key before creating Location Services view

src/MainWindow.vala
Was an artifact of the old way we built the views.
=> No need for a null AppCenter view

src/Utils.vala, src/Views/WelcomeView.vala
Working on the next Pantheon release for NixOS packaging onboarding, I noticed it didn't use our logo.
This fixes that for other downstreams who's icon isn't called "distributor-logo".
=> Get OS logo from os-release

src/Utils.vala
Fixes #65. Can be tested by commenting out the `LOGO` line in `/etc/os-release`.
=> Fallback in logo_icon_name utility method

src/MainWindow.vala
The docs on SettingsSchemaSource get_default say
```
The returned source may actually consist of multiple schema sources from different directories, depending on which directories were given in `XDG_DATA_DIRS` and `GSETTINGS_SCHEMA_DIR`. For this reason, all lookups performed against the default source should probably be done recursively.
```
Without this in NixOS it will not work as intended, as we
have multiple entries in XDG_DATA_DIRS.
=> MainWindow: lookup schemas recursive

src/Views/AbstractOnboardingView.vala, src/Views/AppCenterView.vala, src/Views/NightLightView.vala
Kind of hodge-podge, trying to better optimize for vertical space in preparation for #103. I was gonna do each as a separate branch, but they ended up being tiny.
- Reduces space between header lines
- Aligns AppCenter small text to bottom
- Adds a link to Night Light scheduling/temperature settings since there are more things you could want to tweak, especially if it's night time when you're Onboarding
=> Views: Better use vertical space

src/Views/AppCenterView.vala
"You can sideload ... i.e. from Flathub" sounds as if Flathub was the only sideloading source, but there are others, like GNOME's flatpak repository.
=> AppCenterView: You can sideload "e.g. from Flathub"

src/MainWindow.vala
Fixes #113. Noticed when I was working on #112. To test:
1. `gesttings reset io.elementary.onboarding viewed` to reset to a fresh install
2. Run Onboarding and step through (or skip)
3. In `dconf-editor`, remove one of the feature view names from `io.elementary.onboarding viewed` to simulate a new view showing up in an update; e.g. `location`.
4. Run Onboarding again and see that it shows the update view.
5. Repeat step 3, removing a feature name again.
6. Run Onboarding again.
In master, you will not see the update view again because it has been viewed and thus is removed from the stack. In this branch, you will see the update view again, along with whichever view you deleted from GSettings.
=> MainWindow: Fix update view logic

src/MainWindow.vala
We're getting lots of duplicate issues about things that are covered here again, so I'd like to get this fixed ASAP.
Checks for `Early Access` in the user-facing version string. We can just remove this when we go stable, but this gets it behaving like it did before we switched the codename.
=> MainWindow: Fix Early Access detection

src/MainWindow.vala
This doesn't fix showing the update view when there are no other updates, but at least it makes sure we show the early access view all the time and show it first
=> MainWindow: Show earlyaccess view first

src/Views/EarlyAccessView.vala
Fixes there is some clickable area although no text is shown:
=> EarlyAccessView: Align the project link center

src/Views/AppCenterView.vala
* Use unowned var for contexts
* Make sure we're not translating the link markup
* Use small label style constant
=> AppCenterView: rework labels

po/POTFILES, src/MainWindow.vala, src/Views/OnlineAccountsView.vala, src/meson.build
Closes https://github.com/elementary/onboarding/issues/4
@elementary/ux you are more than welcome to improve the texts 😃️
=> Set Up Online Accounts

src/MainWindow.vala
ButtonBox is dropped in GTK4 so for an easier transition, we can replace it with Box now.
=> Replace ButtonBox with Box for GTK4 Transition

src/MainWindow.vala, src/Views/AbstractOnboardingView.vala, src/Views/StyleView.vala
GTK4 does not accept `expand` and `margin` properties alone anymore. We have to specify them like `margin_start` and `hexpand`.
=> Make Expand and Margin Properties more Specific for GTK4 Porting

src/Switcher.vala
The `on_carousel_changed` signal is not used so it can be safely removed.
=> Remove unused signal

src/Views/StyleView.vala
Fixes a compiler warning
Also, while I'm here, remove a cached preference we never do anything with
=> StyleView: handle NO_PREFERENCE in switch

src/MainWindow.vala
Related to https://github.com/elementary/installer/pull/668
Screenshots are taken on OS 7 daily.
=> MainWindow: warn about daily builds

src/Views/AppCenterView.vala
Doesn't quite fix #129 but try to rework copy here to be clearer about the available options and make sideloading more prominent and obvious
=> AppCenterView: make sideload more obvious and rework copy

src/Views/WelcomeView.vala
* Title area is really heavy so remove OS name. I think less is more here, we don't need to announce the OS name over and over
* Adjust button spacing. We have to take into consideration the vertical spacing from the linkbutton.
=> WelcomeView: adjust button spacing, shorten title

src/MainWindow.vala
If there's not actually any new features, it probably doesn't make sense to show the "What's New" view since there aren't any new features to set up. This makes it so if you're on an Early Access build you just get this after your first run:
=> MainWindow: Only show What's New if there's something other than Early Access

data/meson.build, data/onboarding.metainfo.xml.in, data/prefs.sh, po/POTFILES, src/Application.vala, src/MainWindow.vala, src/Views/AbstractOnboardingView.vala, src/Views/EarlyAccessView.vala, src/Views/GuestView.vala, src/meson.build
Fixes #204
Fixes https://github.com/elementary/triage/issues/144
=> Add GuestView

debian/control
For new housekeeping settings
Depends on:
=> Control: bump runtime depends on Settings Daemon to 1.3.0

src/PageChecker.vala, src/Switcher.vala, src/Views/AbstractOnboardingView.vala
Fixes #217 
Contains a workaround for https://gitlab.gnome.org/GNOME/libadwaita/-/issues/724
For at least what can be fixed within the scope of Onboarding, by making page checker buttons focusable and making sure we only dim the image child, not the focus style
=> Allow focusing PageChecker, scroll to View when it contains focus

src/Views/OnlineAccountsView.vala
Make sure we use the icon that is installed by system settings and not this non-fd.o icon name
=> OnlineAccountsView: use icon shipped with System Settings

.github/workflows/gettext.yml
Same fix with elementary/switchboard-plug-sharing#72
This should fix the gettext actions failing in latest master branch
=> Actions: Make sure to use latest gettext-template; remove git installation

src/MainWindow.vala, src/Views/AbstractOnboardingView.vala
So that there's a non-gesture and non-shortcut way to go back
=> AbstractOnboardingView: replace skip all with back on non-welcome views
