elementary/onboarding

- meson.build
- src/MainWindow.vala
- src/Utils.vala
- src/Views/FinishView.vala
- src/Views/WelcomeView.vala
Update utils class for more OSRELEASE fields
> Get OS support link

- po/POTFILES
- src/MainWindow.vala
- src/Views/AbstractOnboardingView.vala
- src/Views/HouseKeepingView.vala
- src/meson.build
> Add HouseKeepingView

- src/MainWindow.vala
Make it more clear you're not just skipping one step, but everything.
> Skip → Skip All

- src/MainWindow.vala
- src/Views/NightLightView.vala
- src/meson.build
Could use a `night-light` icon https://github.com/elementary/icons/issues/793
> Add Night Light view

- src/Views/HouseKeepingView.vala
- src/Views/NightLightView.vala
Use new icons that just got added
> Change icon names

- src/Views/FinishView.vala
> FinishView: Add docs and get involved links

- data/io.elementary.onboarding.gschema.xml
- data/meson.build
- meson.build
- meson/post_install.py
- src/Application.vala
- src/MainWindow.vala
Using a setting means we that if the user chooses the reset everything to defaults we can be sure that this will run again the next time they begin the session and we don't have to try to delete our own .desktop from autostart or anything crazy
> Auto quit after first run

- src/Views/AbstractOnboardingView.vala
…I thought there were more but I guess it was just this one.
> Use Granite style classes

- meson.build
- src/Application.vala
> Always open from Terminal

- src/Views/FinishView.vala
- src/Views/WelcomeView.vala
> WelcomeView: add images and left align links

- src/Views/FinishView.vala
> Refine Finish copy

- src/Views/AppCenterView.vala
> Make the label of appcenter_button translatable

- po/LINGUAS
> Fix missed lang codes

- data/meson.build
- data/onboarding.appdata.xml.in
- po/extra/POTFILES
> Add AppData

- src/MainWindow.vala
Replaces the hardcoded next button view switch with a dynamically generated list of views
> MainWindow: dynamically go to next view

- src/Views/UpdateView.vala
> Differentiate updates view more

- src/Views/AbstractOnboardingView.vala
- src/Views/UpdateView.vala
> Link to our blog

- src/Views/LocationServicesView.vala
> Clarify Location Services copy

- src/Views/AbstractOnboardingView.vala
- src/Views/UpdateView.vala
> UpdateView: Overlay update icon on logo

- src/MainWindow.vala
Fixes errors when pressing Skip button.
> MainWindow: Don't access removed views

- data/icons/128.svg
- data/meson.build
- data/onboarding.appdata.xml.in
> Add 128px icon

- debian/control
> Control: Use Libhandy-1

- README.md
- src/Views/AppCenterView.vala
Might not want to link directly there, idk.
> AppCenterView: Mention Flatpak and Flathub

- src/Views/HouseKeepingView.vala
> Specify that temp files are unneeded

- src/Views/StyleView.vala
To match elementary/switchboard-plug-pantheon-shell#247
> StyleView: Re-order accent colors

- src/MainWindow.vala
- src/Views/PreReleaseWarningView.vala
- src/meson.build
Closes https://github.com/elementary/onboarding/issues/110
> Add a pre-release warning

- src/Application.vala
Stop trying to load CSS that doesn't exist anymore
> Application: Don't try to load old CSS

- src/Views/StyleView.vala
> Remove unused Granite.Settings

- src/Views/EarlyAccessView.vala
Fixes #143 
We don't have a project board or major known issues right now so just pull that out
> EarlyAccessView: remove outdated copy specific to OS 6

- data/onboarding.appdata.xml.in
- src/Views/HouseKeepingView.vala
Redesign to match Security & Privacy plug, plus downloads
> HouseKeepingView: Redesign and add Downloads

- data/onboarding.appdata.xml.in
- meson.build
> Release 6.1.0

- src/Application.vala
- src/MainWindow.vala
- src/Views/AbstractOnboardingView.vala
- src/Views/WelcomeView.vala
Improve code style so making GTK4 necessary changes is smoother
> Improve Code Style

- debian/control
> Control: update deps for GTK4

- src/MainWindow.vala
- src/PageChecker.vala
Must have been an API change sometime since this was ported :shrug:
> Update carousel to latest LibAdwaita API

- data/StyleView.css
- data/appearance-scheduled.svg
- data/io.elementary.onboarding.gresource.xml
- src/Views/StyleView.vala
Add Dark style shedule preference to fix https://github.com/elementary/onboarding/issues/142
> Add Dark Schedule Preference

- meson.build
> Meson: handy → adw

- data/onboarding.appdata.xml.in
- meson.build
Build is failing in CI due to some kind of container error, but it succeeds locally and in daily launchpad :shrug:
> Release 7.0.0

- src/Views/HouseKeepingView.vala
> Housekeeping: Bind number of days to setting

- src/Views/WelcomeView.vala
> Use Gtk.Box for ImageLinkButton

- src/Views/EarlyAccessView.vala
* Use a list of items instead of bold in a paragraph
* Remove extra label
* Mention feedback
> EarlyAccess: use a list

- src/Views/WelcomeView.vala
Closes https://github.com/elementary/onboarding/issues/209
> WelcomeView: Update description

- src/Views/StyleView.vala
> StyleView: use actual background when available

- src/Application.vala
Make sure to initialize styles with Granite.init
> Application: use Granite.init

- src/MainWindow.vala
- src/Views/AbstractOnboardingView.vala
- src/Views/AppCenterView.vala
- src/Views/HouseKeepingView.vala
- src/Views/NightLightView.vala
- src/Views/StyleView.vala
Keyboard nav is still pretty trash, but at least everything should be read out correctly now
> Improve screenreader support

- data/Application.css
- data/io.elementary.onboarding.gresource.xml
- src/Views/HouseKeepingView.vala
- src/Views/UpdatesView.vala
> UpdatesView: add OS updates

- src/Views/HouseKeepingView.vala
Use settings from https://github.com/elementary/settings-daemon/pull/143
> Housekeeping: use elementary settings daemon

- README.md
- meson.build
Bump libadwaita to 1.4.0 that has NavigationView and NavigationPage that added in #232
> Bump libadwaita version

- data/Application.css
- src/Views/AbstractOnboardingView.vala
- src/Views/WelcomeView.vala
Make sure we set all spacing and margins in CSS so that they scale with text size
> AbstractOnboardingView: move padding, icon size, margin to CSS

- debian/control
> Control: bump settings-daemon dep to 8.0.0

- debian/control
> Control: add libpantheon-wayland-1-dev

- data/onboarding.metainfo.xml.in
- meson.build
> Release 8.0.3

- src/Views/StyleView.vala
> StyleView: wrap sunset-to-sunrise label
